spring.application.name=jenkins-spring-test
server.port=8081

# DATABASE CONNECTION 도커 컴포즈 가상 네트워크 연동 설정
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/my_app_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# DB 드라이버 및 JPA 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update